version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: sqliteproject
    ports:
      - "8081:80"
    depends_on:
      - db
  db:
    image: "sqlitedb"
    volumes:
      - ./Data:/path/in/container/to/mount