version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - db
    command: ["bash", "-c", "dotnet ef database update --project SqLiteProject"]
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  # Geliştirme ortamını etkinleştir
    volumes:
      - ./Data:/app/Data

  db:
    build:
      context: .
      dockerfile: Dockerfile.sqlite
    volumes:
      - ./Data:/path/in/container/to/mount
