# Dockerfile for SQLite
FROM alpine:3.14

# Install SQLite
RUN apk add --no-cache sqlite

# Create a working directory
WORKDIR /data

# Copy the SQLite database file
COPY ./Data/SqliteDb.db /data/

# Command to run when the container starts
CMD ["sqlite3", "SqliteDb.db"]