version: '3.4'

services:
  sqliteproject:
    image: sqliteproject
    build:
      context: .
      dockerfile: SqLiteProject/Dockerfile
    ports:
      - 8082:80
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  db:
    image: alpine:latest
    command: /bin/sh -c "apk add --no-cache sqlite && tail -f /dev/null"
    volumes:
      - ./Data:/data