version: '3.4'

services:
  sqliteproject:
    image: sqliteproject
    build:
      context: .
      dockerfile: SqLiteProject/Dockerfile
    ports:
      - 8082:80
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./Data:/app/Data
  db:
    image: sqlite:latest
    volumes:
      - ./Data:/data